training:
  num_epochs: 10
  batch_size: 32
  learning_rate: 1e-5
  device: 'cuda'
  save_model_path: './clip_model.pth'

data:
  base_path: '/data'

dataloader:
  num_workers: 4
  shuffle: true

loss:
  margin: 0.2

wandb:
  project: 'RKN_DB'
