training:
  num_epochs: 10
  batch_size: 32
  learning_rate: 1e-5
  early_stopping_patience: 3
  device: 'cuda'
  save_model_path: './model.pth'
  model: 'clip'
  loss: 'triplet'

data:
  base_path: '/data'

dataloader:
  num_workers: 4
  shuffle: true

loss:
  margin: 0.2
  temperature: 0.07

wandb:
  project: 'clip-triplet-training'
