training:
  num_epochs: 10
  batch_size: 32
  learning_rate: 1e-5
  device: 'cuda'
  margin: 0.2
  save_model_path: './clip_model.pth'

data:
  base_path: '/data'

dataloader:
  num_workers: 4
  shuffle: true
  drop_last: true

dataloader_val:
  num_workers: 4
  shuffle: false
  drop_last: false

loss:
  margin: 0.3
  hard_negative_ratio: 0.5

wandb:
  project: 'RKN_DB'
