[theme]
primaryColor = "#f63366"
backgroundColor = "#111111"
secondaryBackgroundColor = "#393939"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableStaticServing = true
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
port = 8501